### ISSUE TITLE
Add support for Mac OS 11

### ISSUE THREAD

**Issue by tich91** [ZL-Audio/ZLEqualizer#103]
Hi. Is it possible to run this incredible plugin on Mac OS 11 (aka Big Sur)? On mine it says that is not compatible for unkown reasons.
Thank You

**Comment by zsliu98** [comment]
The manual is pretty clear on this:
> On macOS, the plugin requires Metal support. For some unknown reason, the plugin is not compatible with macOS earlier than macOS 12 (hopefully you can build it locally on macOS 10.15.4).

Another option would be to upgrade your system with https://github.com/dortania/OpenCore-Legacy-Patcher. However, I have no experience in this & not sure whether it will work for this plugin.
