### ISSUE TITLE
[FR]: Make default slope configurable 

### ISSUE THREAD

**Issue by muzzol** [ZL-Audio/ZLEqualizer#108]
### Thanks for taking the time to make a feature request!

- [X] I have read the plugin manual and searched the existing issues.

### Why?

```markdown
current slope for low/hi pass is 12db
```

### What do you want?

```markdown
It would be nice to be able to define default slope for low/hi pass (and any slope related setting).

right now is 12db and I always change it.

thanks a lot for your time.
```

### Code of Conduct

- [x] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
Sure. Default slope should work for low/high pass filters added by double-clicking. I may split the UI setting panel into several tab panels and add it to one of them. Keep this open to remind me of that.

**Comment by zsliu98** [comment]
Completed b232fcd7a62b544a41714acb74392c4a99921771

**Comment by muzzol** [comment]
thanks a lot for keep adding new features to this amazing project !!
