### ISSUE TITLE
[BUG]: ZLEqualiser crashes Reaper in WINE

### ISSUE THREAD

**Issue by RichardJECooke** [ZL-Audio/ZLEqualizer#117]
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
- Plugin version & format: Latest. .exe
- A clear and concise description of what the bug is: Install plugin with latest WINE staging on Ubuntu 24.04. Add plugin as a VST3 FX in a Reaper track. Plugin is a black square and Reaper freezes.
- A clear and concise description of what you expected to happen: Plugin work.s
```

### Additional information

```markdown
- Operating system (& version if applicable): Ubuntu 24.04
- Hardware (CPU & GPU if applicable):
# System Details Report
---

## Report details
- **Date generated:**                              2024-10-11 18:25:39

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. TUF B450-PLUS GAMING
- **Memory:**                                      64.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 2600 × 12
- **Graphics:**                                    NVIDIA GeForce RTX™ 3060
- **Disk Capacity:**                               6.0 TB

## Software Information:
- **Firmware Version:**                            0601
- **OS Name:**                                     Ubuntu 24.04.1 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.8.0-45-generic

- DAW: Reaper latest in WINE
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
Thanks for the info. Have you tried the Linux version of this plugin? Does it work properly?

Be aware that the hardware Windows version (without the software suffix) uses the Direct2D to accelerate GUI. I am not sure whether it is compatible with WINE.

**Comment by RichardJECooke** [comment]
Thanks, no, I gave up on Reaper in Linux with yabridge. It took hours to open a single project and lagged with my keyboard. Reaper in Wine works flawlessly and opens an orchestral template in five minutes so I use that. And Reaper in Wine can't see Linux plugins afaik.

But I just discovered TDR Nova works ok in WINE, I thought it crashed last time I tried. I'll use that for mixing instead instead of ZL.

**Comment by zsliu98** [comment]
> And Reaper in Wine can't see Linux plugins afaik.

Oh, I am not aware of that. Another user has reported a crash with yabridge/WINE before #77.

You may also try the software version (with the software suffix). However, WINE is too complex for me to debug any issue there.

TDR Nova is a great plugin. If ZL does not work on your machine, TDR Nova definitely deserves a try.
