### ISSUE TITLE
[BUG]: Unable to rescale UI after full screen.

### ISSUE THREAD

**Issue by SthaugeAudio** [ZL-Audio/ZLEqualizer#124]
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
- Plugin version & format:
ZL- Equaliser 0.4.2
- A clear and concise description of what the bug is:

I've made an full screen window, maximizing the EQ UI to get some more space for detailed mouse movement. So far I have not been able to rescale the UI back to the normal window. Every time the plugin opens it using a full screen. Dragging the corners to minimise the plugin can be done, but it always revert back to full screen.

I'm not been able to find the settings file to try to delete the full screen option.

- A clear and concise description of what you expected to happen:

Resizing back to normal.
```

### Additional information

```markdown
- Operating system (& version if applicable):
Kubuntu Linux 24.10 with Wayland and Pipewire. 

- Hardware (CPU & GPU if applicable):
Intel i7-13700, Intel® UHD Graphics 770 

- DAW:
Harrison audio Mixbus 10.1 Pro
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
When you drag the corners to minimize the plugin, does the actual plugin window get smaller (e.g., the area of the spectrum gets smaller, the text gets smaller)?

The setting file lies at:
```
~/.config/Audio/Presets/ZL/ZL Equalizer/ui.xml
```
You can delete this file or edit the values `window_h` and `window_w` (probably halve them). Could you please upload the content of this file before you delete/edit it?

**Comment by SthaugeAudio** [comment]
Yes I can resize the window and make it smaller but it get large again if I release the left mouse button. When resizing the window, the ui on zl-eq gets smaler as well but jumps back and forth in size in the window frame and revert back to full screen when releasing the mouse button.

I'll upload the file tomorrow.

**Comment by zsliu98** [comment]
> Yes I can resize the window and make it smaller but it get large again if I release the left mouse button. When resizing the window, the ui on zl-eq gets smaler as well but jumps back and forth in size in the window frame and revert back to full screen when releasing the mouse button.
> 
> I'll upload the file tomorrow.

Thanks a lot for that. When you upload the file, could you please also tell me whether this bug occurs when the window size is smaller than the full-screen size?

**Comment by SthaugeAudio** [comment]
Here's the UI.XML file. I had to rename it to be able to upload it.

I can't change the window size, so it's always full screen. I can change the second icon in the upper right corner though between a full size window or a floating, resize able window, but the  window always fill the entire screen.

After renamed the UI.XML file everything seem ok. I can now resize the window  and the eq fills the window  nicely in any size I choose. So the interesting question is how do I got this problem?

Last, but not least, thank you for all you effort making these nice plugins. 

[ui.txt](https://github.com/user-attachments/files/17487963/ui.txt)

**Comment by zsliu98** [comment]
Technically this should not happen as the plugin will not try to resize itself unless the user drags the bottom-right corner.

However, it is possible that a user accidentally resizes the plugin to a size larger than the screen and can't reach the bottom-right corner. To address this, I have just added a new function to the top-right UI button c24eb412f2556c1901f25c1e1813af1ba1358ee0:

- if you click it, it will open the UI setting panel as usual
- if you click it with command/ctrl, it will resize the plugin windows to the default size

Hopefully this commit will prevent similar bugs in the future.
