### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by richidici** [ZL-Audio/ZLEqualizer#125]
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
- Plugin version & format: Version 0.2.4 Windows Software. Format VST
- A clear and concise description of what the bug is: The double-click to input a specific frequency on FREQ is not working.
- A clear and concise description of what you expected to happen: I expect that by double clicking on FREQ, I can write a specific frequency to work on
```

### Additional information

```markdown
- Operating system (& version if applicable): Windows 11 Home. Version 23H2
- Hardware (CPU & GPU if applicable): 12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz
- DAW: Reaper V7.25
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by richidici** [comment]
didn't press CTRL while double clicking on FREQ...it works fine

**Comment by zsliu98** [comment]
No worries. Once #122 ic completed, you can choose how to open the value editor.
