### ISSUE TITLE
[BUG]: The windows installer version 0.4.4 seems not to work correctly

### ISSUE THREAD

**Issue by JorgeTataArias** [ZL-Audio/ZLEqualizer#131]
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
0.4.4
apparently it does not install vst3
```

### Additional information

```markdown
- Operating system (& version if applicable): Windows 11
- Hardware (CPU & GPU if applicable):
- DAW: Cakewalk Sonar. Reaper
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by JorgeTataArias** [comment]
It may have to do with a positive result from Microsoft's antivirus and it deleting the file.

**Comment by zsliu98** [comment]
I have just installed again on my local Windows 11 and the installation is successful. The action log https://github.com/ZL-Audio/ZLEqualizer/actions/runs/12033108009 also indicates that the VST3 format is packaged into the installer.

I have also uploaded the installer to the VirusTotal and 4 vendors mark it as malicious (AFAICT, previously only 2 vendors would do so). Perhaps those vendors change the detection mechanism. Therefore, I would guess the Microsoft antiviurs is also not happy with the files.

Unfortunately, there is not much I can do. You may clone the repo and build the plugin locally.

I will keep this issue open until the next version in case other people face the same issue.

**Comment by JorgeTataArias** [comment]
That's definitely the problem. I'm going to try to stop the antivirus from deleting it.

**Comment by that1cutie** [comment]
> UPDATE: Solved by preventing the antivirus from deleting it

I apologise if this is too out of the way, but can you describe how you prevented the antivirus from deleting it? so I may follow those steps as well? I seem to be having the same problem.

**Comment by JorgeTataArias** [comment]
I went to the Windows security protection history and it showed "Trojan:Win32/Wacatac.B!ml". I selected "restore" in actions and that's it.


greetings

Jorge


________________________________
De: that1cutie ***@***.***>
Enviado: lunes, diciembre 02, 2024 21:57
Para: ZL-Audio/ZLEqualizer ***@***.***>
Cc: JorgeTataArias ***@***.***>; Author ***@***.***>
Asunto: Re: [ZL-Audio/ZLEqualizer] [BUG]: The windows installer version 0.4.4 seems not to work correctly (Issue #131)


UPDATE: Solved by preventing the antivirus from deleting it

I apologise if this is too out of the way, but can you describe how you prevented the antivirus from deleting it? so I may follow those steps as well? I seem to be having the same problem.
