### ISSUE TITLE
[BUG]: 0.4.4 vst3 on Linux does not show up in Reaper any more

### ISSUE THREAD

**Issue by David-Else** [ZL-Audio/ZLEqualizer#132]
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
0.4.3 Works fine, but 0.4.4 does not show up when scanning for plugins
```

### Additional information

```markdown
- Operating system (& version if applicable): Debian 12
- Hardware (CPU & GPU if applicable):
- DAW: Reaper
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
As I don't have a local Linux machine, I may need help from you. Could you please delete the current plugin and re-install with the following **0.4.3** installer? Does it work with Reaper?

[ZL Equalizer-0.4.3-Linux.zip](https://github.com/user-attachments/files/17994691/ZL.Equalizer-0.4.3-Linux.zip)

**Comment by zsliu98** [comment]
After investigating it a little bit, it truns out that a new library (nlopt) is compiled as a shared library.
```
libnlopt.so.0 => not found
```
I think it is related to CMake configuration. I will try to fix it. Meanwhile, you may compile the code locally to get the VST3 or install the nlopt dependency.

**Comment by David-Else** [comment]
Can I just use the version you linked me, or maybe it has problems?

**Comment by wundermusiker** [comment]
Maybe similar issue in Ubuntu 24.04 with Ardour 8.10. Vst3 is detected, but error is shown inside the plug in manager. 0.43 is confirmed working.

**Comment by zsliu98** [comment]
@David-Else @wundermusiker Would you like to try the following 0.4.5 installer? Does it show up in Reaper/Ardour?

[ZL Equalizer-0.4.5-Linux.zip](https://github.com/user-attachments/files/18000125/ZL.Equalizer-0.4.5-Linux.zip)

I should have read the nlopt documentation more carefully. It is dynamic linked by default.

**Comment by David-Else** [comment]
0.4.5 works :)

**Comment by zsliu98** [comment]
@David-Else Thanks for testing it! I will add 0.4.5 to the changelog and draft the 0.4.5 release soon. You can keep this VST3, which should be identical to the actual 0.4.5 release for Linux.

**Comment by wundermusiker** [comment]
0.45 is now working in Ubuntu 24.04 with Ardour. 👍😎

**Comment by zsliu98** [comment]
@wundermusiker Thanks for letting me know! I am going to close this issue.
