### ISSUE TITLE
[FR]: Ability to change/save default value for "Zero Latency"

### ISSUE THREAD

**Issue by whitespace-rebel** [ZL-Audio/ZLEqualizer#139]
### Thanks for taking the time to make a feature request!

- [X] I have read the plugin manual and searched the existing issues.

### Why?

```markdown
Every time I add ZL Equalizer to a project, it has become a habit to set "Zero Latency = ON".
Most of the time I don't use automation or dynamic EQ, so I would like to avoid setting it up every time.
```

### What do you want?

```markdown
It would be nice to have the ability to save the default value for "Zero Latency" in the config menu / config file.

Thank you!
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
Unlike UI settings (which are shared across all instances), changing the default values of parameters is a function that should be supported by DAW, not by the plugin. Most DAWs can save a preset as the default preset.
If you build it locally, you could change the `defaultI to `1`:
https://github.com/ZL-Audio/ZLEqualizer/blob/main/source/dsp/dsp_definitions.hpp#L433

**Comment by whitespace-rebel** [comment]
Hmm, I thought "Zero Latency" is a UI setting.
For me, loading a preset everytime would be more hassle than just clicking on "Zero LAT".
Also I would like to avoid building a customized plugin.

I just thought a new option could be added, like you already did with the option "Default Pass Filter Slope", which also isn't a UI setting.

**Comment by zsliu98** [comment]
No, you don't have to load a preset each time manually. Once you save the preset as the default preset, the DAWs will load   that preset automatically when you insert a new instance. Most DAWs (Reaper, Pro Tools, etc) support this feature. If your DAW does not support this feature, I would suggest submitting a FR to them.

`Default Pass Filter Slope` is a UI setting. This parameter is NOT visible to DAWs. Once you change it in one instance, you change it in all instances.

However, each instance can have different `Zero Latency` settings. This parameter is visible to DAWs. Therefore, DAWs should manage its default value.

**Comment by whitespace-rebel** [comment]
Thanks for clarifying. I see the difference now.
I'll probably go with a custom build, as my DAW doesn't support loading a default preset automatically.
