### ISSUE TITLE
[FR]: A couple of small suggestions

### ISSUE THREAD

**Issue by yonderehco1197** [ZL-Audio/ZLEqualizer#141]
### Thanks for taking the time to make a feature request!

- [X] I have read the plugin manual and searched the existing issues.

### Why?

```markdown
Hi!

Adding matching makes the plugin an ultimatum solution among all free equalizers and allows you to get close to the functionality of paid analogs. Thank you very much for this opportunity!

I have a few small suggestions:

1. When you double-click on a value before its editor opens, the value is set where the first click went. This is inconvenient and can be dangerous. For example, if I want to enter an output volume value from the keyboard and double-click somewhere on the right side of the slider, the volume level can jump all the way up to +16db and stay that way until I enter and save a new value. This problem affects all horizontal sliders.
You might want to keep only the horizontal drag option, and disable the single click control.

2. Is it possible to make it so that the slope of the filters is taken into account when matching? Sometimes you can see that the result would be much closer to the target curve if some of the points had a slope of 24 db/oct instead of 12 db/oct, for example.
```

### What do you want?

```markdown
Thanks again! :)
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
> When you double-click on a value before its editor opens, the value is set where the first click went. This is inconvenient and can be dangerous. For example, if I want to enter an output volume value from the keyboard and double-click somewhere on the right side of the slider, the volume level can jump all the way up to +16db and stay that way until I enter and save a new value. This problem affects all horizontal sliders. You might want to keep only the horizontal drag option, and disable the single click control.

I am not sure whether it is technically possible because mouse dragging actually starts with a mouse click. However, I could disable right mouse single click control so that you can double click right mouse to open the editor safely.

> Is it possible to make it so that the slope of the filters is taken into account when matching? Sometimes you can see that the result would be much closer to the target curve if some of the points had a slope of 24 db/oct instead of 12 db/oct, for example.

I may add a new fitting model (probably call it `GN+`) to take the slope values into consideration. However, this model will take longer time to converge.

**Comment by zsliu98** [comment]
The `GN+` model is added in 028efdd305bd8ec606e187134b5848cf75d0ae4d. It is not surprising that this model takes a significantly longer time to converge. On my computer `GN` takes less than one second while `GN+` takes up to 5~6 seconds. I may tune it before the formal release.
