### ISSUE TITLE
Collision detection make plugin and host laggy

### ISSUE THREAD

**Issue by ShibuyaCyana** [ZL-Audio/ZLEqualizer#19]
Hi dev: 
Thanks for this wonderful plugin!
Looks like the collision detection is making both plugin and host laggy, running at extremely low frame rate. See the video below:

https://github.com/ZL-Audio/ZLEqualizer/assets/39703247/2298c8e3-802a-4224-9fa8-513306b9fbe1

Above was recorded in REAPER; also tested with FL Studio which gives about the same result.

I'm running ZL Equalizer 0.1.9 on Win11 22621.3155, also tested on my old computer which is on Win10 19044, the problem seems to be a little better, but still exist.

**Comment by zsliu98** [comment]
Looks like a rendering issue. Windows version is based on the JUCE Direct2D preview branch, which is not as stable as the Mac's. I will look into it later to see if I can solve this one or provide a workaround.

**Comment by zsliu98** [comment]
I have just released 0.1.10. Hopefully, the laggy problem will become less severe. Cause the collision detection needs to repaint the whole rectangle, it is really hard to get further improvement on my side. Let's see what JUCE can do with the Direct2D part :)

**Comment by ShibuyaCyana** [comment]
Thanks, but sadly it didn't alleviate this problem :( at least I can't feel any significant improvement.
Doesn't bother me too much anyway, hope JUCE could make it better someday.

**Comment by zsliu98** [comment]
> Thanks, but sadly it didn't alleviate this problem :( at least I can't feel any significant improvement. Doesn't bother me too much anyway, hope JUCE could make it better someday.

I have just realized that collision detection has a thread issue, which may cause the issue you describe. It is fixed in version 0.1.11.
