### ISSUE TITLE
Does not work with AVL-MXe 23.1 “Enlightened"

### ISSUE THREAD

**Issue by Sojuzstudio** [ZL-Audio/ZLEqualizer#25]
Is this meant to work on Debian Bookworm based distros? Complaining about the GlibcXX version. Does not work.

**Comment by zsliu98** [comment]
AFAIK, it is because the plugin is built with a more recent GlibcXX version. I recommend building the source on your machine instead (for Linux dependencies, check [here](https://github.com/juce-framework/JUCE/blob/master/docs/Linux%20Dependencies.md) or follow the GitHub action of this repo).

**Comment by zsliu98** [comment]
#26
