### ISSUE TITLE
Release binaries built with a too new libstdc++ version...

### ISSUE THREAD

**Issue by pms967** [ZL-Audio/ZLEqualizer#26]
```
$ ldd /usr/local/lib/vst3/ZL\ Equalizer.vst3/Contents/x86_64-linux/ZL\ Equalizer.so 
/usr/local/lib/vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /usr/local/lib/vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so)
/usr/local/lib/vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/local/lib/vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so)

```
This happens on Ubuntu 22.04 "Jammy" (latest LTS release) and derived (such as latest version of Mint), as well as Debian Stable, etc.

You've used a way too bleeding edge version of libstdc++... most people will be unable to use your binary release.

Please rebuild them with something older (GLIBCXX_3.4.30, that is libstdc++6 version 12.x or earlier), which are available on most current stable distributions...

**Comment by zsliu98** [comment]
You are correct. The plugin is built with gcc-13, which is not included in Ubuntu 22.04 Jammy (and I have no idea how Clang successfully installed it on Ubuntu 22.04). I will push a hot fix soon.

**Comment by zsliu98** [comment]
https://github.com/actions/runner-images/issues/8659
It seems that GitHub Linux runner will include a newer version of libstdc++ and the most practical solution is to downgrade it manually.

Could you please check whether artifacts from this workflow solve this problem:
https://github.com/ZL-Audio/ZLEqualizer/actions/runs/8414441171

**Comment by pms967** [comment]
> Could you please check whether artifacts from this workflow solve this problem: 

Ehm... I'm no expert with git, and even less (zero...) with building plugins. But, if you can give me some detailed instructions about how to proceed, I'll try to do it.

**Comment by mikelupe** [comment]
Hi - let me chime in.

Unfortunately with the latest binary artefacts, on Debian 12 Bookworm in e.g. Ardour I still get:

"[ERROR]: Could not load VST3 plugin '/home/user/.vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so': /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /home/user/.vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so)"

Of course building/compiling has a similar issue.

**Comment by zsliu98** [comment]
> > Could you please check whether artifacts from this workflow solve this problem:
> 
> Ehm... I'm no expert with git, and even less (zero...) with building plugins. But, if you can give me some detailed instructions about how to proceed, I'll try to do it.

Oh, it seems that you cannot access the artifact from the workflow (I am not familiar with GitHub policies). I will attach the artifact here.

[ZL Equalizer-0.0.0.zip](https://github.com/ZL-Audio/ZLEqualizer/files/14743306/ZL.Equalizer-0.0.0.zip)

**Comment by zsliu98** [comment]
> Hi - let me chime in.
> 
> Unfortunately with the latest binary artefacts, on Debian 12 Bookworm in e.g. Ardour I still get:
> 
> "[ERROR]: Could not load VST3 plugin '/home/user/.vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so': /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /home/user/.vst3/ZL Equalizer.vst3/Contents/x86_64-linux/ZL Equalizer.so)"
> 
> Of course building/compiling has a similar issue.
> 
> edit: We only have GLIBCXX_3.4.30 max on Debian stable. See "strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3". Same btw on Debian unstable (Trixie 13) I think .

That's interesting. I can confirm that after downgrading the highest version of GLIBCXX on GitHub hosted runner is GLIBCXX_3.4.30. And the plugin is runnable on that runner. May I ask whether you are talking about the artifact from the workflow (not from the releases)?

**Comment by mikelupe** [comment]
It was https://github.com/ZL-Audio/ZLEqualizer/actions/runs/8414441171/artifacts/1354353790 (the .zip), not the one from releases.

I'll be able to try again in 0.5h or later on tonight.

**Comment by David-Else** [comment]
I tried https://github.com/ZL-Audio/ZLEqualizer/files/14743306/ZL.Equalizer-0.0.0.zip on Debian 12 in Reaper and it did work initially, then unfortunately it crashed and I needed to do a forced quit, but that was likely a different issue.

**Comment by David-Else** [comment]
> > I tried https://github.com/ZL-Audio/ZLEqualizer/files/14743306/ZL.Equalizer-0.0.0.zip on Debian 12 in Reaper and it did work initially, then unfortunately it crashed and I needed to do a forced quit, but that was likely a different issue.
> 
> funny: we have the same - or at least a very similar - system, but got different results. Maybe the crash has something to do with graphics and/or perhaps it is somehow influenced by the underlying DE? (I'm on KDE plasma here, with compositor disabled - all fancy DE effects disabled... later this evening I'll try again on Mint/Cinnamon).

I was playing with it for quite a while until it crashed. I am using stock Gnome and stock MESA drivers for my AMD Polaris GPU on Debian 12.

This is looking like it could be the best EQ yet with all the features, esp volume matching and collision detection! I hope it becomes stable on Linux ASAP :) I am currently using [TDR Nova](https://www.tokyodawn.net/tdr-nova/) in Wine, but that is not ideal, and I remember I disliked the sound of the oversampling years ago when I did some proper listening tests. I hope there is no oversampling in this one, I want to choose my own sample rate for my projects, and Reaper has oversampling channels if I want to use higher sample rates in a channel. Thanks to the author of this plugin and the amazing power of FOSS!

**Comment by mikelupe** [comment]
- Building from sources is now working on Debian 12 Bookworm, plugin is running as well. 
- Debian 13 Trixie (unstable) I must correct myself, it build and worked as well (froze, see below).

But
- There's indeed hanging of the plugin and the host Ardour after (rather wildly) moving around an EQ point
- KDE Plasma AMD GPU open source drivers

I as well do think this EQ is a very nice plugin feature wise - thanks for your work.

**Comment by Daniele71** [comment]
I tested it a bit on openSUSE TW. no issues to report. Plasma 6 on X11 with amd rx550.
Seriously candidate to be the best open source eq but the automations need to be fixed/supported !
Thanks.

**Comment by David-Else** [comment]
@Sojuzstudio   `libZL Equalizer_SharedCode.a` seems like some unwanted artifact, just forget it exists. Make sure you use https://github.com/ZL-Audio/ZLEqualizer/files/14743306/ZL.Equalizer-0.0.0.zip until a new release comes out with a fix

**Comment by Sojuzstudio** [comment]
Now it works!

**Comment by pms967** [comment]
OK, can confirm that for me it works fine also with Reaper 7.x on Mint 21.x Cinnamon. Oh, in both machines I have Intel (i7 one, i5 the other, both 6th gen) CPUs with integrated GPUs. 

![image](https://github.com/ZL-Audio/ZLEqualizer/assets/16119410/d7ac584b-ab74-4c95-b119-1a6008b7fecc)

**Comment by zsliu98** [comment]
0.1.13 has just been released, which hopefully fixes the libstdc++ version. Thank you guys for working this out with me. I will close this issue this weekend if the libstdc++ version is correct. Besides that,
@David-Else  @mikelupe I would kindly ask you to move to a [discussion](https://github.com/ZL-Audio/ZLEqualizer/discussions/31).
@Daniele71 Although I do not recommend automation, you can still try (as long as you use it properly, plugin crashes should be unlikely).
@David-Else The plugin uses de-cramping (matched filter) instead of over-sampling to obtain better performance. 2x OS will approximately double CPU usage.

**Comment by Daniele71** [comment]
@zsliu98 eq automation is very common. "as long as you use it properly"  what does it means exactly ? bypass, dynamic bypass, and output gain are the less useful automation. Freq and Gain, they are the most useful.

Sorry for the OT.

**Comment by zsliu98** [comment]
> @zsliu98 eq automation is very common. "as long as you use it properly" what does it means exactly ? bypass, dynamic bypass, and output gain are the less useful automation. Freq and Gain, they are the most useful.
> 
> Sorry for the OT.

You can automate them if you want. However, there are some known problems:
- bypass, dynamic bypass, and output gain are real-time safe
- freq, gain, and Q are not real-time safe (my bad), although the plugin passes all parameter automation tests & fuzz tests of `pluginval`
- dynamic on and threshold learning will change other parameters. For example, if you automate both dynamic on and the threshold, I am not sure whether the behavior is well-defined by all DAWs
- if you choose multiple bands from the spectrum, their freq and gain are linked. If you automate two of them, you may also run into problems

**Comment by pms967** [comment]
> As already mentioned, it now builds and works well, until I try to drag an EQ point - at which point it freezes the plugin and the host.

I'm afraid this gonna be tricky to debug: so far, it never happened to me. IIRC, you're using Ardour? May be it is host related? Can you try to run it on Reaper? 

(Though this is OT here... may be it would be better to open a dedicated issue).

**Comment by David-Else** [comment]
@pms967 I am using Reaper, we have a dedicated discussion now: https://github.com/ZL-Audio/ZLEqualizer/discussions/31
