### ISSUE TITLE
LV2 URI

### ISSUE THREAD

**Issue by KottV** [ZL-Audio/ZLEqualizer#32]
Hi!

Current `LV2URI` var in CMakeLists.txt is `https://github.com/ZL-Audio/${PRODUCT_NAME}/tree/${VERSION}`
which is `https://github.com/ZL-Audio/ZL Equalizer/tree/` in result, which is confusing.

I think the correct URI should be like that `https://github.com/ZL-Audio/ZLEqualizer` without space.

**Comment by zsliu98** [comment]
Thanks for the nice catch. I will change `PRODUCT_NAME` to `PROJECT_NAME`. Since I am not familiar with LV2, may I ask whether I should also include the version number in `LV2URI`?

**Comment by KottV** [comment]
Version number is not needed here. It's kind of plugin's ID. So it can be `https://github.com/ZL-Audio/ZLEqualizer` or `https://zl-audio.github.io/plugins/zlequalizer/` or even `zl-audio:zlequalizer`

**Comment by zsliu98** [comment]
Thanks for the link. I have fixed the `LV2URI`. I will fix other repos once I have time.

**Comment by unfa** [comment]
I am not sure if this is relevant, but I had updated the plug-in to 0.3 and the ID changed, because Ardour said it can't find the existing plug-in, and I had to replace it. Thankfully I haven't done any hard work in ZL EQ yet, but I hope that won't be happening more often :D

**Comment by zsliu98** [comment]
@unfa The `LV2URI`is indeed the unique identifier of LV2. If you build the plugin locally before the first release of LV2, you may encounter this problem. I won't change it anymore 😄 
BTW, LV2 format has not been tested (as pluginval does not support that). Please be careful if you use that in production.
