### ISSUE TITLE
ZL Equalizer causes Ableton Live to crash

### ISSUE THREAD

**Issue by Unerium** [ZL-Audio/ZLEqualizer#34]
When I try to use this plugin as a dynamic EQ and change some parameters it causes Ableton Live to crash unexpectedly. Could you please fix that? I would highly appreciate it if you could do that! 🙏

**Comment by zsliu98** [comment]
Did the plugin freeze your DAW? If so, the issue might be similar to #33 . I will keep you updated once I come up with a solution.

**Comment by Unerium** [comment]
The plugin didn't just freeze my DAW, it also caused it to crash.

**Comment by zsliu98** [comment]
> The plugin didn't just freeze my DAW, it also caused it to crash.

Ah, it may depend on how Ableton Live handles locks. I have fixed some known issues and built a new version. Would you like to try this out when you have time?

Similarly, `dmg` is for macOS, and `exe` is for Windows (see attachment).

[ZL Equalizer-0.0.0.dmg.zip](https://github.com/ZL-Audio/ZLEqualizer/files/14802824/ZL.Equalizer-0.0.0.dmg.zip)
[ZL Equalizer-0.0.0.exe.zip](https://github.com/ZL-Audio/ZLEqualizer/files/14802826/ZL.Equalizer-0.0.0.exe.zip)

**Comment by zsliu98** [comment]
No need to try the previous attachment. I have just released the version 0.1.14. Hopefully, this release will fix this issue.
