### ISSUE TITLE
Plugin drives ASIO-GUARD on Cubase very HEAVY

### ISSUE THREAD

**Issue by ZetKaySound** [ZL-Audio/ZLEqualizer#37]
Hy there, 

thx for this great plugin.

there is a very heavy cpu consumption on cubase with the plugin, it drives asio-guard very high. its also higher when gui is open.

i did a demasking tool with all 16 bands enabled, listening to a sidechain with detection circuits set. dropouts get that heavy that it gets hardly usable.

it also would be nice to be able to enable/disable the detection circuit if wanted.

it would also be great to just display the sidechain in addition inside the fft display without having to enable the "headphone" button. maybe in a different color? 

fft display settings don't get saved to cubase presets. i always have to reset my preferences when the plugin gets inserted. it doesn't save those settings inside the "cubase default" setting for the plugin.

again thx for this great plugin.

greetings
zag

**Comment by zsliu98** [comment]
Would you like to try the attachment in #34 when you have time? Do you still observe a similar issue?
If not, does your machine support Metal/Direct2D?

> it also would be nice to be able to enable/disable the detection circuit if wanted.

Could you please explain what is the *detection circuit*?

> it would also be great to just display the sidechain in addition inside the fft display without having to enable the "headphone" button. maybe in a different color?

The plugin always has a sidechain. If you want to display the side-chain spectrum, you have to turn it on in the FFT setting panel. If you press the headphone button, it will solo the corresponding band.

> fft display settings don't get saved to cubase presets. i always have to reset my preferences when the plugin gets inserted. it doesn't save those settings inside the "cubase default" setting for the plugin.

Yes, unlike the window size and the plugin color, the FFT settings don't sync. I may find a way to change the default setting.

**Comment by ZetKaySound** [comment]
> Would you like to try the attachment in #34 when you have time? Do you still observe a similar issue?

don't know if i have done this correct, get virus warning on avast when installing version 0.0.0 and cubase still shows 0.1.13. but if it does, it's still the same

> If the issue still occurs, does your machine support Metal/Direct2D?

don't know what you mean with this, how can i verify? i use nvidia 1060 gc.

> Could you please explain what is the _detection circuit_?

with detection circuit (thats how it's also called in the kirchoff-eq) is the little rectangle on the bottom, where you set on which frequency of the sidechain the eq-band should listen to. with this we can set a high frequency band to also listen to bassy stuff of the sidechain channel. But forget about the idea to enable/disable it. my thought was to save cpu without it but i think, this is always listening to the bands frequency with the q-setting. it would be wrong to listen to the full spectrum on a specific band. 

> The plugin always has a sidechain. If you want to display the side-chain spectrum, you have to turn it on in the FFT setting panel. If you press the headphone button, it will solo the corresponding band.

Oh OK sorry, i might have missed this one.

**Comment by zsliu98** [comment]
> > Would you like to try the attachment in #34 when you have time? Do you still observe a similar issue?
> 
> don't know if i have done this correct, get virus warning on avast when installing version 0.0.0 and cubase still shows 0.1.13. but if it does, it's still the same
> 
> > If the issue still occurs, does your machine support Metal/Direct2D?
> 
> don't know what you mean with this, how can i verify? i use nvidia 1060 gc.
> 
> > Could you please explain what is the _detection circuit_?
> 
> with detection circuit (thats how it's also called in the kirchoff-eq) is the little rectangle on the bottom, where you set on which frequency of the sidechain the eq-band should listen to. with this we can set a high frequency band to also listen to bassy stuff of the sidechain channel. But forget about the idea to enable/disable it. my thought was to save cpu without it but i think, this is always listening to the bands frequency with the q-setting. it would be wrong to listen to the full spectrum on a specific band.
> 
> > The plugin always has a sidechain. If you want to display the side-chain spectrum, you have to turn it on in the FFT setting panel. If you press the headphone button, it will solo the corresponding band.
> 
> Oh OK sorry, i might have missed this one.

AFAIK your machine should support Direct2D. Since Cubase seems to be unhappy with the current version, I would kindly suggest trying the next formal release instead.
I understand the term *detection circuit* now. You are correct, disabling the detection circuit won't save much CPU usage since dynamic filter calculation is much more time-consuming.

**Comment by zsliu98** [comment]
I have just released the version 0.1.14. Hopefully, this release will fix this issue.

**Comment by ZetKaySound** [comment]
> I have just released the version 0.1.14. Hopefully, this release will fix this issue.

WOW, i now did a comparison with the kirchoff eq and it seems that you did it. it runs much more smooth and there is no peaks in asio-guard. you fixed it, great !! thanks a lot for this. 

i think this plugin will blow-viral soon, its growing as a pro-q/kirchoff killer and it's unbelievable that this is a free plugin. really great. it grew quickly into my plugin chain, nothing more needed in addition.

i would like to share some more ideas for this if you don't mind. as the pro-q/kirchoff killer, i think it would be a very killer option to add a feature that would also grow as another big leap into killing another plugin - sooth2.

what if you would implement "spectral compression" to the eq bands. you would pull up a eq-band, set a very steep slope for it to have a linear threshold, activate the spectral compression mode with some button and then it would act like sooth2, compressing down every single frequency that exceeds the threshold. the threshold setting also could be the negative gain setting of the eq band. i often use this on harsh cymbals, its a great method of smothing out those outstanding frequencies, to push them into a more "unharsh" state, works also great on high gain - heavy distorted guitars. pulling up the q-factor of the band to the max of the spectrum could also be used to act as a full range "spectral compressor" and how awesome would be, if it also could be triggered by the sidechain channel.

i think, no other plugin does it like that, functionality maybe leads to the same outcome, but the workflow is different.

i also know that this isn't done in some few days. would be killer to have such a "all in one" tool.

some other thoughts that you might have had yourselfes:
-transparency and color settings for the different fft analyzer curves and lines.
-maybe also for the grid-lines.
-some method for "more fine-adjusting" of settings on the gui-buttons for mousewheel edit (like maybe holding the "shift" key).
-when activating the dynamic mode on a band, the gain and q-factor devide into 2 different values, it might be more practical to have 2 different sliders for those values, to have an instant access to those different values (speeds up workflow)
-short tooltips when hovering over buttons.
-maybe more options to change colors, but hey, that isn't an important function.

again i just want to thank you for this great plugin. i really love it, it's a game changer for beeing free.

thanks
zag

**Comment by zsliu98** [comment]
Thanks for your valuable feedback.

> what if you would implement "spectral compression" to the eq bands

That is a cool idea. AFAIK spectral compression is a completely different thing. If one day I want to implement this, I will release another plugin instead.  BTW, there is already a [FOSS spectral compressor plugin](
https://github.com/robbert-vdh/nih-plug/tree/master/plugins/spectral_compressor) from nih-plug.

> transparency and color settings for the different fft analyzer curves and lines.
maybe also for the grid-lines.
maybe more options to change colors, but hey, that isn't an important function.

It is on the [road map](https://github.com/orgs/ZL-Audio/projects/1?pane=issue&itemId=57435417).

> some method for "more fine-adjusting" of settings on the gui-buttons for mousewheel edit (like maybe holding the "shift" key).

I have already implemented it (maybe in the next release if I am happy with it).

> when activating the dynamic mode on a band, the gain and q-factor devide into 2 different values, it might be more practical to have 2 different sliders for those values, to have an instant access to those different values (speeds up workflow)

Ah, cause the space of the plugin is rather valuable, I won't put them into different sliders. Instead, you may use left/right mouse button to drag those values in one slider (or directly on the spectrum).

> short tooltips when hovering over buttons.

I will think about it.

I am going to close this issue. Feel free to re-open it.
