### ISSUE TITLE
Menu issues on Linux

### ISSUE THREAD

**Issue by therealfumbles** [ZL-Audio/ZLEqualizer#38]
Hi

Many thanks for your hard work on this collection of plugins. It's really cool to have these available :)

I have built all of them for linux and they all have one common issue with the dropdown menus. I guess it's some kind of transparency bug (perhaps due to the lack of hardware acceleration on linux?)

It's easier to see on one of the others like ZLEComp: 

![Screenshot from 2024-03-29 15-08-01](https://github.com/ZL-Audio/ZLEqualizer/assets/86084089/43354491-64c7-49f2-8319-0ab30e2e4413)

But it is also present in ZLEqualizer, though the shadow / background is much smaller so it only shows as white corners:

![Screenshot from 2024-03-29 15-09-17](https://github.com/ZL-Audio/ZLEqualizer/assets/86084089/a699dfce-9c70-421a-b50e-1ebb44af6320)

The other UI elements work fine. It's just the dropdown menus that have an issue.

I also spotted a typo in the Collision menu: Strength is Stength.

**Comment by zsliu98** [comment]
Thanks for the feedback. The white corners have different sizes cause I removed the outside shadow of dropdown menus in the ZLEqualizer. However, the lack of hardware acceleration does not seem to be the reason. ZLEComp on Windows (without hardware acceleration) does not have such issues. I have no idea at this point.

Some similar issues on Logic:
https://forum.juce.com/t/bug-popup-menu-background-and-logic-silicon/43243

I am going to refactor other plugins in the future. Hopefully, they won't have such large white borders after that. BTW ZLEComp has dozens of known issues. I'd advise you against using it in production.

The typo has been fixed :blush:
