### ISSUE TITLE
Mouse wheel, allow small steps

### ISSUE THREAD

**Issue by Daniele71** [ZL-Audio/ZLEqualizer#39]
Hi,  changng rotary values with mouse wheel is complicated, jump to much. Maybe with key combination like shift wheel, allow small steps.

Also, show rotary values when you move pointer on the graph.

Thanks.

**Comment by zsliu98** [comment]
I have added the fine adjustment to the project roadmap.
I don't think actual values are necessary when moving the dragger. Therefore, I use pitch notation instead of the actual freq value.
