### ISSUE TITLE
link to a file on a personal computer

### ISSUE THREAD

**Issue by trebmuh** [ZL-Audio/ZLEqualizer#40]
https://github.com/ZL-Audio/animator/blob/1836239545ad48910c363dab6ae92d28ecd2b897/Source/.clang-format#L1C25-L1C25

It does sounds strange for this to be a link to a file on a personal computer

**Comment by zsliu98** [comment]
Yes, it is indeed very strange. I think it was uploaded accidentally from bgporter's computer. I will remove this link to make the library clean (at my repo, since bgporter does not respond to pull requests).
