### ISSUE TITLE
Static gain compensation for more accurate results

### ISSUE THREAD

**Issue by 0CCULTIST** [ZL-Audio/ZLEqualizer#42]
A more accurate solution for gain compensating static EQ bands is as following:

A static output gain is to be applied based on the frequency, gain & Q of a single band. At 2khz, the amount of gain compensation is roughly half of the inverse of the band. 
So, a bell boost of 6db at 2khz will apply a static ~-3db gain to the output. 
As you go higher up the spectrum, the amount of gain compensation lessens. Likewise, ultra-low frequency boost/cuts don't necessitate as much gain compensation on the output. 
Bell cuts should be compensated slightly less in general as it's easy for the entire spectrum become too loud. 

Hi/Lo-cut filters shouldn't be compensated at all for the same reason we lessen the compensation of bell cuts, just the issue is magnified (potentially) infinitely.

Q affecting the gain should be simple to implement, I don't know the specific formula though.

A note for lessening the gain compensation around the bass region; this should be done very low down in the spectrum to avoid bad results with sub-heavy music. TDR SlickEQ starts slightly lowering the compensation at around 300hz, and then sharply at around 30hz.

Examples of plugins which, more or less, use the method I have described are: SlickEQ M, Pulsar Massive & AOM factory EQs. 

Overall, this method leads to fairly effective results without any of the uncertainties of dynamic processing. If it fails to work, it's as simple as a manual adjustment from the user, which most are accustomed to anyways.

Dynamic bands are a different story. Personally, I'm not a fan of AGC in general, whether it be in a dynamic EQ or a single band compressor, however, if we want to keep this feature to help with dynamic band compensation I'd imagine it'd be best to have AGC _after_ all of the static gains are applied to potentially correct any mistakes from static gains, getting the most out of the dynamic process per-say.

**Comment by zsliu98** [comment]
Thanks for the valuable feedback. AFAIK, there are two methods of gain(loudness) compensation:
- static method: We first make some assumptions about the input signal. After that, we can use a weighting curve to determine the amount of compensation. It won't change the dynamic. However, it is not accurate.
- dynamic method: We put one meter at the input and one meter at the output. Then we calculate the difference between two loudness, smooth the difference, and apply the compensation. It is accurate (in the long term). However, it changes the dynamic (for static EQ, this might cause an audible side effect).

I am afraid that we need more experiments to determine the formula of static gain compensation. I *may* add a static method in the future (probably after finishing the UI setting panel).

https://github.com/orgs/ZL-Audio/projects/1/views/1?pane=issue&itemId=58934654

**Comment by zsliu98** [comment]
The pre-release 0.2.0 now includes this feature. You can enable static gain compensation from `Output` -> `SGC`. `SGC` only works for `Peak`, `Low Shelf`, and `High Shelf`. The amount of compensation might be less than expected as I am not very certain about the algorithm.
