### ISSUE TITLE
Selecting high pass 6dB/oct makes high pass low pass

### ISSUE THREAD

**Issue by David-Else** [ZL-Audio/ZLEqualizer#43]
Using [0.1.16](https://github.com/ZL-Audio/ZLEqualizer/releases/tag/0.1.16) LInux VST3:

- create a high pass filter (it defaults to 12 dB)
- select 6 db per octave and it becomes a low pass

![image](https://github.com/ZL-Audio/ZLEqualizer/assets/12832280/ce1d87e8-0d65-4f1a-a8c1-6b728fb184f0)

![image](https://github.com/ZL-Audio/ZLEqualizer/assets/12832280/f2db0111-cd22-4b24-a507-b92a2befdcbc)

**Comment by zsliu98** [comment]
Thanks for reporting! I have just fixed the bug locally. It will be fixed in the next release (hopefully with the UI setting panel).

**Comment by zsliu98** [comment]
Hi! This bug should be fixed in the pre-release 0.2.0. Would you like to verify it when you have time?
