### ISSUE TITLE
GUI and host very low performance since JUCE updates(?)

### ISSUE THREAD

**Issue by mikelupe** [ZL-Audio/ZLEqualizer#49]
On Linux (Debian/KDE/X11) there is a massive graphics lag with the plugin (concerning as well the host's Ardour GUI) since about a week.

It must have happened in the past week, but I'm not sure if it was after d72acee or only after 23f4fcd . I guess the probability is high that it could be related to the JUCE update, what do you think?

**Comment by zsliu98** [comment]
I also observed graphics lag on macOS after the commit 3bafe86cfd7dc3d2b3d42c14ab19e935354c88fb, i.e., updating to JUCE 8. If it is the same case for you, it must be due to this JUCE **major** update. I will try to figure it out and report it to the JUCE team. Hopefully, they can fix it then while adjusting/explaining the new EULA :astonished:
I also observed an increase in the final binary releases :) don't know why either, but also seems problematic

**Comment by zsliu98** [comment]
I have just created a `juce7` branch (the only difference is JUCE itself and one line JUCE8 related code). Would you like to try the `juce7` branch if you have time?

**Comment by mikelupe** [comment]
I just built the juce7 branch and it still feels and looks very laggy. I as well can hear the CPU fan running higher.

**Comment by zsliu98** [comment]
> I just built the juce7 branch and it still feels and looks very laggy. I as well can hear the CPU fan running higher.

Did you observe the lag when dragging/changing a filter? Or the lag happens even if nothing is done (e.g., only several static filters with FFTs)? It is strange cause the UI-related code (of this repo) hasn't changed that much since last week ... BTW, did you also update submodules when checking out the `juce7` branch?

**Comment by mikelupe** [comment]
That was it - I now cleaned and repulled everything -> lag is gone.

**Comment by zsliu98** [comment]
> That was it - I now cleaned and repulled everything -> lag is gone.

Then it is a JUCE 8 issue. And it is the same on my macOS. I will report it to the JUCE team.

**Comment by mikelupe** [comment]
Let's cross fingers

**Comment by mikelupe** [comment]
btw I only tested VST3 under Linux with JUCE8 - I could test LV2 with it as well tomorrow.

**Comment by zsliu98** [comment]
> btw I only tested VST3 under Linux with JUCE8 - I could test LV2 with it as well tomorrow.

No need to do that. Both VST3 and AU have the same issue. LV2 won't be the lucky one.
BTW, I have also removed some dirty & unsuccessful workarounds from branch `juce7`. You may pull & build again if you use this plugin.

**Comment by mikelupe** [comment]
Commit c32637c in "main" is juce8? Because it feels quite snappy now...

**Comment by zsliu98** [comment]
> Commit [c32637c](https://github.com/ZL-Audio/ZLEqualizer/commit/c32637c7ce9b9c1cb2fd2db0eb65cf4e5eada8c9) in "main" is juce8? Because it feels quite snappy now...

Unfortunately, it is JUCE 7 :sweat: I will stick to JUCE 7 in the next (few?) months since the bugs in JUCE 8 make me painful.

**Comment by mikelupe** [comment]
Haha - good choice :) You've got a chance to find time concerning realtime safety in the near future?

**Comment by zsliu98** [comment]
> Haha - good choice :) You've got a chance to find time concerning realtime safety in the near future?

The real-time safety issue should be solved in 0.1.14. Have you experienced crashes or audio pops/clicks since then? The rendering issue (when automation is activated) is nothing related to real-time safety. It is because the plugin and the DAW are both using CPU to render (and for some reason in the same thread). *According to advertising, JUCE 8 Webview can obtain instant cross-platform hardware accelerated graphics via WebGL.* But I am afraid that the whole Webview thing still needs some time.

**Comment by mikelupe** [comment]
I see - I indeed thought the missing rt safety was the reason for the host UI lagging when moving the EQ points. No, I haven't got any pops nor clicks.

Well, it is what it is. I'm not sure I'd be too keen on WebGL. But I though even with juce7 it should be possible to multithread it, it really is strange.

Anyway, thanks for your efforts again.

**Comment by mikelupe** [comment]
Funny enough, that's exactly what I tried some 2-3hrs ago, as I saw you integrated the refresh rate. And yes, on lowest it helps indeed.

Do you think you'll find a solution for the threading thing in the next few weeks or months? It would really be a pitty, if this would hinder it to become one of the contenders of plugin of the year :)

Thanks for your work

**Comment by zsliu98** [comment]
> Funny enough, that's exactly what I tried some 2-3hrs ago, as I saw you integrated the refresh rate. And yes, on lowest it helps indeed.
> 
> Do you think you'll find a solution for the threading thing in the next few weeks or months? It would really be a pitty, if this would hinder it to become one of the contenders of plugin of the year :)
> 
> Thanks for your work

Pre-release 0.2.0 not only integrates the refresh rate but also puts the majority of path updating to a background thread (you may pull the code again since there have been several commits in the last few hours). And you may increase the refresh rate until the host is not happy with that.
AFAIK, there is no way to multithread the `paint()` function (which now only contains `g.strokePath()` or something alike). The only way to make `g.strokePath()` faster is to use hardware acceleration (on Linux, it means OpenGL/WebGL).

**Comment by mikelupe** [comment]
Yeah, that's what I did, and it felt indeed smooth, I already had played around with the different levels of refresh rate, and as mentioned it indeed helps.

> The only way to make g.strokePath() faster is to use hardware acceleration (on Linux, it means OpenGL/WebGL).

You already explained that , my bad.

**Comment by zsliu98** [comment]
A quick update: I have bumped JUCE to JUCE 8 and it works OK on my local macOS and Windows. I have also adjusted the GUI part a little bit, which may improve the performance (especially during automation).

You may build it locally (make sure you also update JUCE) or download the pre-release 0.3.2.

**Comment by mikelupe** [comment]
Unfortunately under Linux the performance is worst case again here, even without automation. As soon as I try to open the GUI, everything stalls. Refresh rate is already set to 25fps. I pulled everthing incl. JUCE. Maybe I'll find some time to check closer on it this weekend.

**Comment by mikelupe** [comment]
Unfortunately I do have this on two different machines - stalling is quite strong, more or less the same as when you had it on Mac. There must be a way. What opengl and Mesa (on Mac? no idea) library versions do you have installed?

**Comment by zsliu98** [comment]
> Unfortunately I do have this on two different machines - stalling is quite strong, more or less the same as when you had it on Mac. There must be a way. What opengl and Mesa (on Mac? no idea) library versions do you have installed?

Thanks for the feedback. The Metal version of my macOS is Metal 3.

Would you like to try the branch `juce7` when you have time? (or the binary from https://github.com/ZL-Audio/ZLEqualizer/actions/runs/9553093036) Currently, I am still uncertain about the cause of the stalling (JUCE 8 or some *improvements*? I have made in 0.3.2).

BTW, does the previous version 0.3.1 have the stalling issue?

**Comment by mikelupe** [comment]
The stalling only came back with 0.3.2.

**Comment by mikelupe** [comment]
I just rebuild the juce7 branch and there it's ok (without automation, the stalling there remains when automating)

**Comment by zsliu98** [comment]
> I just rebuild the juce7 branch and there it's ok (without automation, the stalling there remains when automating)

It is an awkward situation. JUCE 8 has GUI issues on Linux while JUCE 7 GUI does not perform well on Windows ... Perhaps I shall build with JUCE 7 for Linux and build with JUCE 8 for Windows and *wait for* JUCE to solve this problem in 8.0.1 :worried:

**Comment by mikelupe** [comment]
That's an awful situation and quite painstaking for you to handle, but it could be the best. Is the JUCE "team" already aware about these issues?

**Comment by zsliu98** [comment]
> That's an awful situation and quite painstaking for you to handle, but it could be the best. Is the JUCE "team" already aware about these issues?

I reported it in April ... *maybe* they have been aware of this. Cause I can't read the low-level GUI code, I am not able to provide a detailed report to them.

**Comment by mikelupe** [comment]
Maybe you could approach https://github.com/baconpaul , he's strongly involved in several projects like https://github.com/surge-synthesizer/surge , https://github.com/surge-synthesizer/shortcircuit-xt/commits/main/ and helps Airwindows' Chris out with https://github.com/baconpaul/airwin2rack/ . I don't know him personally, but I think he's quite JUCE affine - you never know :)

**Comment by mikelupe** [comment]
Lately building the juce7 branch with git checkout 7.0.12 in the JUCE directory under Linux gives similar/same bad performance like when building the juce8/main branch. What could potentially happen here? 

I cleanup the git folders, so am cloning anew to be sure.  Very strange

**Comment by zsliu98** [comment]
> Lately building the juce7 branch with git checkout 7.0.12 in the JUCE directory under Linux gives similar/same bad performance like when building the juce8/main branch. What could potentially happen here?
> 
> I cleanup the git folders, so am cloning anew to be sure. Very strange

0.3.3 does not touch the GUI part (except add a button in the `General` setting). Besides that, the size of the binary release also indicates that it is on the same juce7. If you have time, you may try the following things:

- download & install the released binary. How is the performance?
- checkout 0.3.2 on the `juce7` branch and build it again. How is the performance?

**Comment by mikelupe** [comment]
My bad, after pulling the juce7 branch and checking out JUCE 7.0.12, I then did a "git submodule update --init" which I guess reset JUCe to the default 8 again. Sorry the noise, it's back to normal performance.

Still, couldn't you bind the submodule to automagically checkout 7.0.12 in the juce7 branch? There wouldn't be the need for another version in that branch, or would it?

**Comment by zsliu98** [comment]
> My bad, after pulling the juce7 branch and checking out JUCE 7.0.12, I then did a "git submodule update --init" which I guess reset JUCe to the default 8 again. Sorry the noise, it's back to normal performance.
> 
> Still, couldn't you bind the submodule to automatically checkout 7.0.12 in the juce7 branch? There wouldn't be the need for another version in that branch, or would it?

If both branches have the same submodule version, the pull request will be easier. But I do see the building process might be confusing. I have changed it to 7.0.12 now.

**Comment by mikelupe** [comment]
Thank you - that works fine, just tested.

**Comment by mikelupe** [comment]
I guess the graphical stutters und Linux, when moving around the EQ points, is tied to JUCE 8 not yet being implemented for the Linux builds. As this is not a showstopper for using this great EQ, and the original issue was solved a long time ago, I guess closing this is best.

Thanks again for this powerfull EQ
