### ISSUE TITLE
(Linux) VST3 Plugin window size locked to a too large amount

### ISSUE THREAD

**Issue by mikelupe** [ZL-Audio/ZLEqualizer#54]
**OS**: Linux Debian, KDE Plasma X11

In git head I have some strange behaviour on the plugin window size, where it got stuck at _h=950 / w_=1859 without being able to reduce the size. Even when using the plugin "internal" corner resize tool to drag it smaller, it jumped back. 

So I had to edit $HOME/.config/Audio/Presets/ZL/ZL\ Equalizer/ui.xml , in order to bring it back again to a reasonable size.

> `<PARAM id="window_h" value="450"/>`
`<PARAM id="window_w" value="690"/>`

Could a "Reset window size to default" button in the UI section make sense? And choosing a default size, which could be usable as well on e.g. 1600x900 wide laptop screens?

**Comment by zsliu98** [comment]
Hi, I have just pushed a fix that may resolve this issue. It seems that some old code from my previous plugin is problematic :expressionless:

The default window size is `w=740,h=440`, which should be usable on a 1600x900 screen. And any resizing will modify the values in `ui.xml`, which should be used as the default size next time. Therefore, an additional button might not be necessary.

**Comment by mikelupe** [comment]
Thank you, I'll check in some minutes.

I realized the realtime nature, as I watched ui.xml while resizing. There's something maybe only on Linux. I'll report after testing.

**Comment by mikelupe** [comment]
fix confirmed - works flawlessly now.

**Comment by mikelupe** [comment]
Fix confirmed.

**Comment by mikelupe** [comment]
p.s. w=740,h=440 is indeed enough for everything
