### ISSUE TITLE
ZLEqualizer missing out on GitHub topics (and being found through them)?

### ISSUE THREAD

**Issue by hartwork** [ZL-Audio/ZLEqualizer#57]
Hi!

I heard about ZLEqualizer through commit 1059bc85f65339e6c8fcfc691f5821b06ca8b018 and the related CI issue…

I noticed that the Git repository does not have an topics associated. Here's what it looks like for https://github.com/libexpat/libexpat and where to find the related button if interested:

![topics_Screenshot_20240519_150955](https://github.com/ZL-Audio/ZLEqualizer/assets/1577132/04551537-2211-4ceb-872c-0e5e58f56000)

![topics_2_Screenshot_20240519_151343](https://github.com/ZL-Audio/ZLEqualizer/assets/1577132/145349b1-143c-4965-b5d2-08ab29b43c7f)

The auto-completion in there helps finding the right topic names, e.g. whether it's `audio-effects` or `audio-effect` (singular). What do you think?

Best, Sebastian

**Comment by zsliu98** [comment]
Thanks for the suggestion. I have added several topics to this repo.
> I heard about ZLEqualizer through commit https://github.com/ZL-Audio/ZLEqualizer/commit/1059bc85f65339e6c8fcfc691f5821b06ca8b018 and the related CI issue…

:open_mouth: that surprises me
