### ISSUE TITLE
Always is taking me out when I tray to get on in collision

### ISSUE THREAD

**Issue by Mike4810** [ZL-Audio/ZLEqualizer#58]
Hello!

It is good when is working but when I try to active the collision it is taking me out of my Daw even without any other plugin, can you fix please!

Thank you your plugin is amazing just that is the problem.

**Comment by zsliu98** [comment]
Yes, the collision detection might have some problems ... I am going to look into this. This problem should be fixed in the next release `0.3.0`. However, it may take some time as some new features are coming. I will inform you when a pre-release is available.

**Comment by Mike4810** [comment]
I forgot to say, is working in a one project but when I try to open it in other project always happens this, but it was happening since the first time just maybe after 10 times it accepted de collision at the first try, but now never! I have been trying more than the first time but always take me out of my DAW

**Comment by Mike4810** [comment]
Awesome I really thankful.

**Comment by zsliu98** [comment]
@Mike4810 The pre-release 0.3.0 is available. Would you like to check whether it fixes this bug?

**Comment by zsliu98** [comment]
Fixed in `0.3.1`.
