### ISSUE TITLE
Inconsistent or missing plug-in metadata

### ISSUE THREAD

**Issue by unfa** [ZL-Audio/ZLEqualizer#62]
Hi!

It seems like ZL Eq's LV2 and VST3 versions are named differently: "ZLEqualizer" vs "ZL Equalizer".
Also the author and tags are missing in Ardour's plug-in manager.

I'd also suggest to change the tags to "effect, equalizer, compressor" rather than "plugin" :D

![obraz](https://github.com/ZL-Audio/ZLEqualizer/assets/491704/a7b95950-e2b1-43a2-ae5c-015f29d4af78)

**Comment by zsliu98** [comment]
For a JUCE plugin, there are two names:

- project name: cannot have spaces
- product name: can have spaces

For this plugin, the project name is `ZLEqualizer` and the product name is `ZL Equalizer`. And Ardour defines the `File/ID` for VST3 and LV2 differently:

>  File/ID | Displays the file name for LADSPA, VST2, and VST3, as well as the ID for LV2 and AU

On my local macOS, Ardour shows the `Name` and the `Creator` of VST3 correctly.

<img width="809" alt="Screenshot 2024-05-28 at 16 42 36" src="https://github.com/ZL-Audio/ZLEqualizer/assets/35594091/00ffff3b-4dc8-4287-86bc-5f8a65e927c2">

___

Unfortunately, I don't know how to add tags to this plugin through JUCE. It seems that this feature is not supported by JUCE CMake API. If you know how to do this or have a JUCE example, it would be very helpful.
