### ISSUE TITLE
Middle mouse scroll doesn't work at all sometimes

### ISSUE THREAD

**Issue by acc4github** [ZL-Audio/ZLEqualizer#63]
How to reproduce:
1. Open ZL instance in a mixer
2. Make a band
3. Switch windows focus to other things in FL studio (e.g Playlist)
4. Go back to ZL window and try to adjust Q with middle mouse scroll

* It starts to work again after you close the ZL window and reopen it (without completely removing it in the mixer)

**Comment by zsliu98** [comment]
Thanks for reporting. I can replicate this bug locally. It also happens if you select & deselect & select a band. It will get fixed in `0.3.1`.

**Comment by zsliu98** [comment]
Hi! The pre-release 0.3.1 is ready. This issue should be fixed.

**Comment by acc4github** [comment]
Yes, I tested it and it's fixed. Thanks for the update!
