### ISSUE TITLE
Feature request: Add Visual Feedback for Automatic Gain Compensation (AGC)

### ISSUE THREAD

**Issue by David-Else** [ZL-Audio/ZLEqualizer#66]
AGC (Automatic Gain Compensation) is an amazing feature, but it can be challenging to determine when it is active and how it is affecting the audio levels. Sometimes I switch it on and off and the levels don't seem to change, it would be much more valuable if it had visual feedback to show it in action.

To enhance the usability of AGC, I propose adding a small meter that displays a single number indicating the difference between the input and output levels. While AGC is actively adjusting the levels, the meter should be red. Once AGC has stabilized and the output is steady, the meter can turn green. This visual feedback would allow users to confirm AGC's operation and effectiveness.

The meter should be prominently displayed in the main interface to ensure it is visible as adjustments are made.

Thanks for the great plugin!

**Comment by zsliu98** [comment]
> While AGC is actively adjusting the levels, the meter should be red. Once AGC has stabilized and the output is steady, the meter can turn green.

No, AGC will never become *stable*. When it is on, it calculates the difference of RMS before & after filters, passes that difference through a smoother, and applies the smoothed difference. Cause AGC will introduce harmonics and may cause unexpected results(artifacts), I would suggest turning that off and applying a static output gain manually once you finish your adjustment.

Cause the main panel is for filters, I don't want to put AGC values on that. Perhaps an input/meter would be the perfect place for AGC values. However, I am not sure whether an equalizer needs that ...

**Comment by David-Else** [comment]
Thanks for the info! I still think having the volume change that the AGC is applying visible would be very useful, even if it is never stable.

> I would suggest turning that off and applying a static output gain manually once you finish your adjustment.

It would be great to know that value from the AGC so it could be used for the static output gain, then it would be easy to quickly turn the filter on and off for volume matched a/b testing.

**Comment by zsliu98** [comment]
It is now on the `main` branch. When you change `Gain Colour` to non-transparent in the UI setting panel, the current gain (summation of AGC, SGC, and the output gain) will show up per 1.5s at the output setting button.
