### ISSUE TITLE
Crashing/Lagging 

### ISSUE THREAD

**Issue by YoBro012** [ZL-Audio/ZLEqualizer#73]
The plugin is heavily lagging. I am facing this issue recently (windows). When I open my session and click the plugin the whole plugin freezes up along with the daw. After that can't do anything with it( even can't close it). I have to close the whole project session by "end task" from task manager. Any fix ??

**Comment by zsliu98** [comment]
Would you like to share the OS info (Win10 or Win11) and the plugin version? Do 0.3.1 and 0.3.2 both freeze the DAW or only 0.3.2?

**Comment by YoBro012** [comment]
My OS is Win10. Initially I was using 0.3.1 version. I thought that if I did an update, this problem would go away. But after updating to 0.3.2 still facing this issue. Everything remains fine until I try to open and tweak something in this plugin Sent from Mail for Windows From: zsliu98Sent: Sunday, June 30, 2024 11:15 PMTo: ZL-Audio/ZLEqualizerCc: YoBro012; AuthorSubject: Re: [ZL-Audio/ZLEqualizer] Crashing/Lagging (Issue #73) Would you like to share the OS info (Win10 or Win11) and the plugin version? Do 0.3.1 and 0.3.2 both freeze the DAW or only 0.3.2?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by zsliu98** [comment]
> My OS is Win10. Initially I was using 0.3.1 version. I thought that if I did an update, this problem would go away. But after updating to 0.3.2 still facing this issue. Everything remains fine until I try to open and tweak something in this plugin Sent from Mail for Windows From: zsliu98Sent: Sunday, June 30, 2024 11:15 PMTo: ZL-Audio/ZLEqualizerCc: YoBro012; AuthorSubject: Re: [ZL-Audio/ZLEqualizer] Crashing/Lagging (Issue #73) Would you like to share the OS info (Win10 or Win11) and the plugin version? Do 0.3.1 and 0.3.2 both freeze the DAW or only 0.3.2?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

@YoBro012 Hi! Unfortunately, I fail to reproduce the same issue on my Win11 with Reaper. This issue may be cause by different software environment or hardware. Here are some steps that may help:

1. Check Windows (& 
firmware?) updates and also install the [Latest Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170). Try this plugin again.

2. Try the following installer (static-link C++ runtime). Does the plugin work?
[ZL Equalizer-0.0.0-Windows-Static.zip](https://github.com/user-attachments/files/16073597/ZL.Equalizer-0.0.0-Windows-Static.zip)

3. Try the following installer (built with JUCE 7, i.e., with software render). Does the plugin work?
[ZL Equalizer-0.0.0-Windows-JUCE7.zip](https://github.com/user-attachments/files/16073599/ZL.Equalizer-0.0.0-Windows-JUCE7.zip)
