### ISSUE TITLE
.clap format

### ISSUE THREAD

**Issue by RustoMCSpit** [ZL-Audio/ZLEqualizer#75]
https://github.com/free-audio/clap-juce-extensions

**Comment by zsliu98** [comment]
I will wait for the official CLAP support from JUCE. Since most DAWs should support at least one of VST3/AU/LV2, CLAP is not necessary at this point.

**Comment by Bram-Brooks** [comment]
Sorry to revive this old thread, but is there any more progress about this? Me and I'm sure a lot of other people would appreciate a CLAP version. Thanks in advance.

**Comment by zsliu98** [comment]
@Bram-Brooks JUCE still does not support CLAP officially. It was advertised as a planned feature of JUCE 9, so hopefully soon :)
