### ISSUE TITLE
Crashing on Windows (even with latest C++ redist)

### ISSUE THREAD

**Issue by that1cutie** [ZL-Audio/ZLEqualizer#78]
I haven't updated since version 0.1.13 until today. Today I updated to 0.3.2. When I tried to load it into FL,  its little window said that the plugin failed to load and to make sure it was installed properly before FL Studio crashed altogether. It didn't give any other details. For the time beeing I've downgraded to 0.1.13 again.

**Comment by zsliu98** [comment]
Hi! Thanks for reporting. If you have any ongoing projects, please stay with the current version.

Would you like to download the PluginDoctor https://ddmf.eu/plugindoctor/ (the demo version would be enough) and load the ZL Equalizer 0.3.2 in the standalone PluginDoctor application? Does it show up correctly? How about 0.3.1?

**Comment by that1cutie** [comment]
I apologise for not coming back to this. I think I have figured out the issue, and I believe it is related to the way that FL Studio saves plugin states, and not an issue with ZL EQ. Unfortunately right around that time, both of my computers stopped working correctly and I have not been able to test this, but I'm just now getting them working again and will report my findings when I can.
