### ISSUE TITLE
Validation Problem On Logic X on Mac Big Sur 11.6.8

### ISSUE THREAD

**Issue by Daboz84** [ZL-Audio/ZLEqualizer#84]
### What happened?

```markdown
- Plugin version: ZL Equalizer 3.3
- A clear and concise description of what the bug is: The plugin cannot be open on Logic X
- A clear and concise description of what you expected to happen: After following all the plugin installation procedure I got a message from Logic X saying that the plugin is not compatible with Logic X. In the plugin manager I got another message that says that the plugin cannot be open.
```

### Additional information

```markdown
- Operating system MAC OS Big Sur 11.6.8 :
- DAW:Logic Pro X 10.4.1
```

### Relevant log output

```shell
This is the error I get: validating Audio Unit ZL Equalizer by ZL:

    AU Validation Tool
    Version: 1.8.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aufx' - 'Equa' - 'Zliu'
--------------------------------------------------
Manufacturer String: ZL
AudioUnit Name: ZL Equalizer
Component Version: 0.3.3 (0x303)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF


validation result: couldn’t be opened
```

**Comment by zsliu98** [comment]
Thanks for the report. macOS compatibility is always an issue here. I am on the latest macOS version and Github has discontinued the macOS 11 runner image. If you know about CMake, the most reliable solution is to build the plugin on your machine.

Could you please install both AU and VST3 of ZL Equalizer 0.3.3 and load them in [Plugin Doctor application](https://ddmf.eu/plugindoctor/) (the demo version would be enough). Does AU/VST3 show up correctly? If not, could you please also try the AU in the attachment in Plugin Doctor?

[ZL Equalizer.component.zip](https://github.com/user-attachments/files/16268991/ZL.Equalizer.component.zip)

**Comment by Daboz84** [comment]
Thanks for your answer! I will try to do it next week.

Best regards
Davide

Il giorno mer 17 lug 2024 alle ore 17:58 zsliu98 ***@***.***>
ha scritto:
