### ISSUE TITLE
[BUG]: Freeze by trying to resize (Win 10, Ableton 12 & 12.1b4)

### ISSUE THREAD

**Issue by Clicac** [ZL-Audio/ZLEqualizer#85]
### What happened?

```markdown
- Plugin version: 0.3.3
- A clear and concise description of what the bug is:
When loaded on a track, the Plugin loads correctrly and seems to work. If I try to resize the plugin-window with the handle in the lower right corner, the plaug/the complete DAW freezes and I have to kill the Win-process.
- A clear and concise description of what you expected to happen:
The plugin windows should reszize
```

### Additional information

```markdown
- Operating system (& version is applicable): Windows 10 Home 22H2, with current c++ runtime
- DAW: Ableton Live 12.0.10 and 12.1b4
```

**Comment by Clicac** [comment]
Addition: As you reccommended (see Bug #73, https://github.com/ZL-Audio/ZLEqualizer/issues/73#issuecomment-2204267724), for me the JUICE7 Version did the trick: Can resize, no more freeze (Ableton 12.1b4).

**Comment by zsliu98** [comment]
Thanks for the report. I would guess that JUCE 8 Direct2D rendering does not work well with some hardware.

Would you like to play with the JUCE 7 version for a while? If it does work well, I will add a JUCE 7 Windows version to the next release.
