### ISSUE TITLE
ZL EQ[BUG]: 

### ISSUE THREAD

**Issue by leonsmits479** [ZL-Audio/ZLEqualizer#89]
### What happened?

```markdown
- Plugin version:ZL Equalizer
- I installed ZL Equalizer on my mac (BIGSUR) but Cubase dit not recognise the VST3 plugin. On your website is mentioned that it will work from OS11, installation went ok.
- A clear and concise description of what you expected to happen: Hope you can tell me what is wrong
```

### Additional information

```markdown
- Operating system (& version is applicable): BIG SUR ver 11.7.10
- DAW: Cubase 13
```

**Comment by zsliu98** [comment]
See #84 

You may try the installer in the attachment (AU only) and the attachments in the above link.

THe most reliable solution is to the source on your local machine.

[ZL Equalizer-0.0.0-macOS.dmg.zip](https://github.com/user-attachments/files/16455704/ZL.Equalizer-0.0.0-macOS.dmg.zip)

**Comment by leonsmits479** [comment]
Hi,
Thank you for fast reply, but i think Cubase can only can work with VST3, so i don't know if i understand you answer well.
Installation on MAC went ok and VST3 file was in the right folder, but Cubase does not recognise the VST3 ZL Equaliser. Other third party VST3 plugins are recognised correctly.

Kind Regards Leon

Kind Regards Leon

**Comment by zsliu98** [comment]
@leonsmits479 I forgot Cubase is from Steinberg ... Anyway, here is another installer with VST3 only. The main problem is that the binary does not handle compatibility very well on old machines (although I have tried my best).

This one is built on a macOS 12 machine, which is the oldest one I can access through Github. Unfortunately, as an independent developer, I do not have access to any macOS 11 machine.

Hopefully this will work for you.

Yours,

[ZL Equalizer-0.0.0-macOS.dmg.zip](https://github.com/user-attachments/files/16458685/ZL.Equalizer-0.0.0-macOS.dmg.zip)

**Comment by leonsmits479** [comment]
Hi,

Thank you for your reply, i tried new download, but unfortnetly it does not work either. I hoped it could work....

Kind Regards leon

**Comment by zsliu98** [comment]
@leonsmits479 Thanks for testing that out. Unfortunately, I am not able to provide further help on this. I will update the website shortly.

Yours.
