### ISSUE TITLE
[BUG]: Problem changing UI color

### ISSUE THREAD

**Issue by JorgeTataArias** [ZL-Audio/ZLEqualizer#94]
### What happened?

```markdown
- Plugin version:0.3.4
- A clear and concise description of what the bug is: Problem changing UI color
- A clear and concise description of what you expected to happen: 
Changing the UI colors and moving the plugin window returns to the previous settings while moving it and returns when releasing the window. If you close the window and then reopen it, everything works as it should.. 
if need it, i have video of the problem
```

### Additional information

```markdown
- Operating system (& version is applicable): WIN11
- DAW: Cakewalk Sonar
```

**Comment by zsliu98** [comment]
Thanks for reporting.
I am not sure whether I understand the issue correctly. Would you like to try the installer in the attachment? If the issue still exists, could you please upload the video to a cloud driver (e.g., Google Drive) and share the link?

[ZL Equalizer-0.0.0-Windows.exe.zip](https://github.com/user-attachments/files/16571368/ZL.Equalizer-0.0.0-Windows.exe.zip)

**Comment by JorgeTataArias** [comment]
***@***.*** sent you 1112.gif

1 item, 20.7 MB in total ・ Expires on 14 August, 2024


Download link:
https://wetransfer.com/downloads/6eb8ca4110d2edd3c262431a0660500d20240811023707/0b90dc8036cc421ec066dd60b35d47cb20240811023707/dac064?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid



Message:
video problem changing UI color



1 item

1112.gif - 20.7 MB


[Sent through WeTransfer Pro](https://wetransfer.com/pricing?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal/terms


To make sure our emails arrive, please add ***@***.*** to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by JorgeTataArias** [comment]
Hi,

Unfortunately, the installer you sent me doesn't seem to fix the problem. Here I send a video with the problem, prior to the installer you sent. You will notice that sometimes it happens and other times it doesn't.
https://we.tl/t-AM4h5YKkQy
1112.gif<https://we.tl/t-AM4h5YKkQy>
1
 file sent via WeTransfer, the simplest way to send your files around the world
we.tl



________________________________
De: zsliu98 ***@***.***>
Enviado: sábado, agosto 10, 2024 23:17
Para: ZL-Audio/ZLEqualizer ***@***.***>
Cc: JorgeTataArias ***@***.***>; Author ***@***.***>
Asunto: Re: [ZL-Audio/ZLEqualizer] [BUG]: Problem changing UI color (Issue #94)


Thanks for reporting.
I am not sure whether I understand the issue correctly. Would you like to try the installer in the attachment? If the issue still exists, could you please upload the video to a cloud driver (e.g., Google Drive) and share the link?

ZL Equalizer-0.0.0-Windows.exe.zip<https://github.com/user-attachments/files/16571368/ZL.Equalizer-0.0.0-Windows.exe.zip>

**Comment by zsliu98** [comment]
I see the issue. It is so strange. Once a new setting is saved, there is no way to retrieve the previous setting. My best guess is that the rendering engine caches the previous painting function(?). I will report it to the JUCE team.
