### ISSUE TITLE
[FR]: UI Reset to default

### ISSUE THREAD

**Issue by Fabi-tech-1991** [ZL-Audio/ZLEqualizer#96]
### Why?

```markdown
I changed the UI in a way i dont like, and i wanted to reset it to the default, but there is no way to go back to the standart UI which cam with the installation.

Am i just blind?

the two arrows besides the save button behave like a Undo button, but once i saved my settings i do not find a way to go back to the default settings.

Can you help me?

Thank you very much

Fabi
```

### What do you want?

```markdown
i want a Button, "restore default UI"
```

**Comment by zsliu98** [comment]
This is the expected behavior of the current version. The undo button will only undo UNSAVED settings. When you save, there is no way to go back.

Your FR is great. I *may* rework the reset button so that it will reset to the default colours (no guarantee).

If you do want to reset now, delete the following file:

- On Windows, "\Documents and Settings\username\Application Data\Audio\Presets\ZL\ZL Equalizer\ui.xml".
- On the Mac, "~/Library/Audio/Presets/ZL/ZL Equalizer/ui.xml".
- On GNU/Linux, "~/.config/Audio/Presets/ZL/ZL Equalizer/ui.xml".".

**Comment by zsliu98** [comment]
It is easier than I expected, see commit 6187f8e. You could build it locally or download the installer from the latest action workflow. Otherwise, please kindly wait for the next patch version.

**Comment by Fabi-tech-1991** [comment]
Thank you very much for your quick response. unfortunately i have no idea how to build this myself, since i am not a coder.
If you dont mind, and if its not that complicated, could you explain to me, step by step what i have to do, or give me a link where i can donwload the installer from the latest action workflow. to make it work?

I did not yet manage to get the newer version you made, but i want to explain, how i would like the UI Options for me to feel intiuitive..

I will start with explaining whats strange for me
For me it is a bit strange, that i have to safe the UI Chnages, without having the possibility to try them.
Right at the moment, i can change a parameter and i have to guess how this will result. i only see the result if i press safe, but then when i safed it i can not go back. in my opinion, this does not really make sense

This is how i would like it to work: 
when i change a setting, i want it to show results immediately. then when i like the result, i may safe or i may undo.

Example:

I change the shadow color from white to red. i see it directly. i dont like it, so i can press undo.
Then i change it to green. I like it. Then i safe. 

if i am not happy with all the changes i applied, i would like to have a reset button to get back to default settings.

other then that, i think its a great plugin!!!!

Thank you very much

**Comment by zsliu98** [comment]
> Thank you very much for your quick response. unfortunately i have no idea how to build this myself, since i am not a coder.
> If you dont mind, and if its not that complicated, could you explain to me, step by step what i have to do, or give me a link where i can donwload the installer from the latest action workflow. to make it work?

Since you have no background in coding, an installer would be a much easier solution. Could you tell me your platform and plugin format?



> I change the shadow color from white to red. i see it directly. i dont like it, so i can press undo. Then i change it to green. I like it. Then i safe.
> 
> if i am not happy with all the changes i applied, i would like to have a reset button to get back to default settings.

An undo button would be a bit more complex since it has to track the history of changes. I won't support it in the near future.

**Comment by Fabi-tech-1991** [comment]
> Since you have no background in coding, an installer would be a much easier solution. Could you tell me your platform and plugin format?

**>Sure, i am on mac Sonoma 14.5 using ableton. I use AU (and VST). I was told, that AU was made for mac particularly and therefore is the more stable format so i think AU would be great.**

thanks

**Comment by zsliu98** [comment]
> > Since you have no background in coding, an installer would be a much easier solution. Could you tell me your platform and plugin format?
> 
> **>Sure, i am on mac Sonoma 14.5 using ableton. I use AU (and VST). I was told, that AU was made for mac particularly and therefore is the more stable format so i think AU would be great.**
> 
> thanks

See attachment. It is marked as version 0.0.0 because it is not a formal release. BTW, there is also a new feature in this version. If you press the button "A", it will not only start dynamic threshold learning but also change the threshold over time, i.e., the threshold will be program-dependent.

[ZL Equalizer-0.0.0-macOS.dmg.zip](https://github.com/user-attachments/files/16647078/ZL.Equalizer-0.0.0-macOS.dmg.zip)

**Comment by Fabi-tech-1991** [comment]
Works like a charm! Thank you
